name = "tiktokvd"
main = "cfbuild.js"
compatibility_date = "2026-05-09"
account_id = "797dab1d6110bd918702c990034a4e9a"

routes = [
  { pattern = "tk.0d000721.cv/*", zone_name = "0d000721.cv" }
]

workers_dev = true